[package]
name = "mandelbrot"
version = "0.1.0"
authors = ["Roman Levin <rlevin@egnyte.com>"]

[dependencies]
num = "0.1.27"
rayon = "1.0"
actix-web = "0.6.7"
serde = "1.0"
serde_derive = "1.0"
glium = "*"

[dependencies.image]
version = "0.19.0"
default-features = false
features = ["png_codec"]
